### ISSUE TITLE
Allow Cmd-Enter evaluation for Mac users

### ISSUE THREAD

**Issue by lambdahands** [zodiac/isicp#43]
Hey, I'm really digging this project. I noticed I have to run `Ctrl-Enter` to evaluate code; however, a common convention is to allow Mac users to use `Cmd-Enter` as well.

I noticed your'e using CodeMirror, and from a previous previous commit that solves #11, you could do something like this:

```js
editor.setOption('extraKeys', {'Cmd-Enter': function() {
  editor.getOption("onBlur")();
}});
```

Thoughts?

**Comment by zodiac** [comment]
Fixed in yuanchenyang/coding-js@b20a53c7bb967d42a73fef6393416bb7f317cc2d
