### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by gilch** [zodiac/isicp#45]
<title>404 Not Found</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Not Found</h1>
<h2>The requested URL <code>/isicp/index.html/</code> was not found on this server.</h2>
<h2></h2>

Tried the **^ <>** at the top of the page, but **^** doesn't work. I think it should point to "/isicp/" instead.

**Comment by zodiac** [comment]
Fixed in 5f92abc5b726648cc156acdfb9046aea0df25862
