### ISSUE TITLE
Equations don't render

### ISSUE THREAD

**Issue by gilch** [zodiac/isicp#46]
![image](https://cloud.githubusercontent.com/assets/3346292/6856946/f3906192-d3c8-11e4-8b88-6e69db513598.png)

This is from 1-1-elements.html rendered in Chrome.
**Edit:** I just noticed a "load unsafe scripts" icon in Chrome. That seems to fix the rendering problem, and it enables the green sidebar which wasn't showing properly before. Is there a way to make the scripts "safe"? Or at least make a note of it so people know they have to enable the scripts manually?

**Comment by zodiac** [comment]
fixed in a3e1aa88b1bcf5bef4ab8d9a64cd251b4e46e55c
